### ISSUE TITLE
why not installed?

### ISSUE THREAD

**Issue by gongchangyou** [jbrule/matomoplugin-CampusGeoIP#1]
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/2409053/161260765-0812ea2b-4a56-491b-b0d1-7ddd32d3ad83.png">

i have already installed campus geo ip

![image](https://user-images.githubusercontent.com/2409053/161260790-80fc4bab-c4fe-4b35-9dda-60a654c0ca37.png)

**Comment by jbrule** [comment]
There is a check for population of locations and networks. The locations need to be manually defined in MySQL with a tool like Sequel Ace. There is a CLI task that can populate the networks using your network manifest via http

**Comment by MrCodeB2** [comment]
Hi Josh!
Thanks for providing this plugin :-)
There is only one problem, i am stuck with the load of the networks.
So i want to try to load the info also using sql but i am not sure about the format i need to put into network_start and network_end.
Can you provide an example?
best regards
Konrad

**Comment by jbrule** [comment]
> Hi Josh! Thanks for providing this plugin :-) There is only one problem, i am stuck with the load of the networks. So i want to try to load the info also using sql but i am not sure about the format i need to put into network_start and network_end. Can you provide an example? best regards Konrad

network_start and network_end are the lowest and highest IP addresses in the network. (NOT IN CIDR FORMAT)

You need to get the IP address into binary format (this was required to support 128bit IPv6 addresses). The import processor uses PHPs inet_pton function for that. MySQL >= 5.6.3 has INET6_ATON. If you don't a version of MySQL with support there is a suggestion here https://stackoverflow.com/questions/24266272/get-value-from-mysql-stored-with-inet-pton
`UNHEX(HEX(CAST(INET_ATON(ipaddress) AS UNSIGNED)))
-- same as
INET6_ATON(ipaddress)`

You'd assign the output of that to the database fields.

**Comment by jbrule** [comment]
@MrCodeB2 Can you try network import again with version 4.1.3?

**Comment by jbrule** [comment]
Provided suggestion regarding import binary IP formats into MySQL. Closing.
