### ISSUE TITLE
Question regarding external access sites

### ISSUE THREAD

**Issue by jcasarini** [jbrule/matomoplugin-CampusGeoIP#12]
Hi!
Is it possible to use this plugin in combination with DBIP / GeoIP2 (php)?

We have sites that are accessed both internally and externally, and we would like to geolocate both entries.

Is there a way to setup this plugin to catch all internal IPs loaded into the DB and pass on the rest to the other geo provider?

Thanks!

Joaquín

**Comment by jbrule** [comment]
Yes a fallback IP location provider feature was added in version 4.1.6. If CampusGeoIP can't resolve an IP it is passed on to a fallback provider you can specify in settings https://github.com/jbrule/matomoplugin-CampusGeoIP/releases/tag/4.1.6

**Comment by jcasarini** [comment]
Thanks!
