### ISSUE TITLE
French / Belgium regions

### ISSUE THREAD

**Issue by rockyluke** [jbrule/matomoplugin-CampusGeoIP#5]
Thanks for your work, it's very helpful 🙏 

Quick question about region : according to https://en.wikipedia.org/wiki/ISO_3166-2:FR French region have three letters code (the main one), so I chose to use the numerical code, which work great with Matomo, but I would like to know / ensure that I did well.

If **not**, could it be acceptable to change de table schema to 3 (or maybe more) chars for region ? (I'll try locally)

Thanks for you help on that.

**Comment by jbrule** [comment]
That should be fine as long as Matomo handles it correctly. If your test is
successful please submit a pull request with updated CREATE TABLE
statement.

Josh

**Comment by jbrule** [comment]
Might be best to use varchar(3 or 4).

**Comment by rockyluke** [comment]
After 24H of test, it's working well. Here is the PR : https://github.com/jbrule/matomoplugin-CampusGeoIP/pull/6

**Comment by rockyluke** [comment]
Fixed on https://github.com/jbrule/matomoplugin-CampusGeoIP/pull/6. Thanks :pray:
